export default {
  PASSWORD_RULES: [
    v => !!v || "Password is required",
    v => (v && v.length >= 8) || "Password must be 8 characters or more"
  ],
  EMAIL_RULES: [
    v => !!v || "E-mail is required",
    v => /.+@.+\..+/.test(v) || "E-mail must be valid"
  ],
  REQ_RULES: [v => !!v || " required"],
  COUNTRIES: [
    "Afghanistan",
    "Albania",
    "Algeria",
    "American Samoa",
    "Andorra",
    "Angola",
    "Anguilla",
    "Antarctica",
    "Antigua and Barbuda",
    "Argentina",
    "Armenia",
    "Aruba",
    "Australia",
    "Austria",
    "Azerbaijan",
    "Bahamas (the)",
    "Bahrain",
    "Bangladesh",
    "Barbados",
    "Belarus",
    "Belgium",
    "Belize",
    "Benin",
    "Bermuda",
    "Bhutan",
    "Bolivia (Plurinational State of)",
    "Bonaire, Sint Eustatius and Saba",
    "Bosnia and Herzegovina",
    "Botswana",
    "Bouvet Island",
    "Brazil",
    "British Indian Ocean Territory (the)",
    "Brunei Darussalam",
    "Bulgaria",
    "Burkina Faso",
    "Burundi",
    "Cabo Verde",
    "Cambodia",
    "Cameroon",
    "Canada",
    "Cayman Islands (the)",
    "Central African Republic (the)",
    "Chad",
    "Chile",
    "China",
    "Christmas Island",
    "Cocos (Keeling) Islands (the)",
    "Colombia",
    "Comoros (the)",
    "Congo (the Democratic Republic of the)",
    "Congo (the)",
    "Cook Islands (the)",
    "Costa Rica",
    "Croatia",
    "Cuba",
    "Curaçao",
    "Cyprus",
    "Czechia",
    "Côte d'Ivoire",
    "Denmark",
    "Djibouti",
    "Dominica",
    "Dominican Republic (the)",
    "Ecuador",
    "Egypt",
    "El Salvador",
    "Equatorial Guinea",
    "Eritrea",
    "Estonia",
    "Eswatini",
    "Ethiopia",
    "Falkland Islands (the) [Malvinas]",
    "Faroe Islands (the)",
    "Fiji",
    "Finland",
    "France",
    "French Guiana",
    "French Polynesia",
    "French Southern Territories (the)",
    "Gabon",
    "Gambia (the)",
    "Georgia",
    "Germany",
    "Ghana",
    "Gibraltar",
    "Greece",
    "Greenland",
    "Grenada",
    "Guadeloupe",
    "Guam",
    "Guatemala",
    "Guernsey",
    "Guinea",
    "Guinea-Bissau",
    "Guyana",
    "Haiti",
    "Heard Island and McDonald Islands",
    "Holy See (the)",
    "Honduras",
    "Hong Kong",
    "Hungary",
    "Iceland",
    "India",
    "Indonesia",
    "Iran (Islamic Republic of)",
    "Iraq",
    "Ireland",
    "Isle of Man",
    "Israel",
    "Italy",
    "Jamaica",
    "Japan",
    "Jersey",
    "Jordan",
    "Kazakhstan",
    "Kenya",
    "Kiribati",
    "Korea (the Democratic People's Republic of)",
    "Korea (the Republic of)",
    "Kuwait",
    "Kyrgyzstan",
    "Lao People's Democratic Republic (the)",
    "Latvia",
    "Lebanon",
    "Lesotho",
    "Liberia",
    "Libya",
    "Liechtenstein",
    "Lithuania",
    "Luxembourg",
    "Macao",
    "Madagascar",
    "Malawi",
    "Malaysia",
    "Maldives",
    "Mali",
    "Malta",
    "Marshall Islands (the)",
    "Martinique",
    "Mauritania",
    "Mauritius",
    "Mayotte",
    "Mexico",
    "Micronesia (Federated States of)",
    "Moldova (the Republic of)",
    "Monaco",
    "Mongolia",
    "Montenegro",
    "Montserrat",
    "Morocco",
    "Mozambique",
    "Myanmar",
    "Namibia",
    "Nauru",
    "Nepal",
    "Netherlands (the)",
    "New Caledonia",
    "New Zealand",
    "Nicaragua",
    "Niger (the)",
    "Nigeria",
    "Niue",
    "Norfolk Island",
    "Northern Mariana Islands (the)",
    "Norway",
    "Oman",
    "Pakistan",
    "Palau",
    "Palestine, State of",
    "Panama",
    "Papua New Guinea",
    "Paraguay",
    "Peru",
    "Philippines (the)",
    "Pitcairn",
    "Poland",
    "Portugal",
    "Puerto Rico",
    "Qatar",
    "Republic of North Macedonia",
    "Romania",
    "Russian Federation (the)",
    "Rwanda",
    "Réunion",
    "Saint Barthélemy",
    "Saint Helena, Ascension and Tristan da Cunha",
    "Saint Kitts and Nevis",
    "Saint Lucia",
    "Saint Martin (French part)",
    "Saint Pierre and Miquelon",
    "Saint Vincent and the Grenadines",
    "Samoa",
    "San Marino",
    "Sao Tome and Principe",
    "Saudi Arabia",
    "Senegal",
    "Serbia",
    "Seychelles",
    "Sierra Leone",
    "Singapore",
    "Sint Maarten (Dutch part)",
    "Slovakia",
    "Slovenia",
    "Solomon Islands",
    "Somalia",
    "South Africa",
    "South Georgia and the South Sandwich Islands",
    "South Sudan",
    "Spain",
    "Sri Lanka",
    "Sudan (the)",
    "Suriname",
    "Svalbard and Jan Mayen",
    "Sweden",
    "Switzerland",
    "Syrian Arab Republic",
    "Taiwan",
    "Tajikistan",
    "Tanzania, United Republic of",
    "Thailand",
    "Timor-Leste",
    "Togo",
    "Tokelau",
    "Tonga",
    "Trinidad and Tobago",
    "Tunisia",
    "Turkey",
    "Turkmenistan",
    "Turks and Caicos Islands (the)",
    "Tuvalu",
    "Uganda",
    "Ukraine",
    "United Arab Emirates (the)",
    "United Kingdom of Great Britain and Northern Ireland (the)",
    "United States Minor Outlying Islands (the)",
    "United States of America (the)",
    "Uruguay",
    "Uzbekistan",
    "Vanuatu",
    "Venezuela (Bolivarian Republic of)",
    "Viet Nam",
    "Virgin Islands (British)",
    "Virgin Islands (U.S.)",
    "Wallis and Futuna",
    "Western Sahara",
    "Yemen",
    "Zambia",
    "Zimbabwe",
    "Åland Islands"
  ],
  CATEGORIES: [
    "Governance, Legal & Compliance and Reporting",
    "Operations & Infraorganisation",
    "Strategy & Planning",
  ],
  PILLARS: [
    "Exploration & Growth",
    "Operational & Capital Excellence",
    "Marketing & Sales",
    "HR",
  ],
  SUB_CATEGORIES: [
    "Expansions & Investments",
    "Schedule/Costs (Projects)",
    "Capital & Operating Budget ",
    "Life of Mines & Plants",
    "Price & Demand",
    "Corporate Social Responsibility & Sustainability (CSR)",
    "Political & Government Relations",
    "Financial",
    "Envoinment",
    "Health & Safety",
    "Exploration (Resources & Reserves)",
    "Production",
    "Supply Chain & Logistics",
    "Sales, Marketing & Customer Interaction",
    "Legal & Compliance",
    "Human Resources",
    "Exploration & Mining Licenses",
    "Mergers & Acquisitions",
    "Strategy & Business Planning",
  ],
  DESCRIPTIONS: [
    "No Selection",
    "Risk 2",
    "Exploration & mining licenses not granted for new territories or revoked for existing territories",
    "Failure of exploration to: a) Add/secure new resources, b) Extend life of existing mines (LOM)",
    "Lack of high cost smelter curtailments (Specially in China)",
    "Execution & completion of capital projects within time and cost",
    "Inability to achieve production & growth targets ",
    "Loosing social license to operate",
    "Improper project closeout, handover & operations readiness",
    "Uncertainty with geological resource estimation for new project.",
    "Automotive growth in US & Europe doesn’t materializes",
    "Insurable risks not insured",
    "Beneficiation Plant is not producing Rock Phosphate in sufficient quantity and Quality",
    "Plant Performance is inadequate to meet the production target as per the design",
    "Inability to meet customer requirements",
    "Non-availability of Critical materials/Services or concentration of suppliers",
    "Uninterrupted Power supply",
    "Lack of a proper employee documentation/archiving system that prevent information losses and insecurity",
    "Security Risk (inadequate security arrangements & permits)",
    "Cash Shortage",
    "Caustic Supply to Refinery",
    "Commissioning and Production Risk Rolling Mill ",
    "New Regulation",
    "Diminishing head grades/low grades of mineralization (Grade erosion/depletion)",
    "Mined Ore Delivery ",
    "Utilizing the cash disbursed through advance payment to vendors.",
    "Adverse environmental incident",
    "Non - performance of Insurance to mitigate identified and insured risk (other affiliates)",
    "Failure to renew the insurance policies on a timely basis (other affiliates)",
    "​Delay in claims processing and payments",
    "Information systems are vulnerable to breach of security and inappropriate discloser of sensitive information to unauthorized personnel",
    "​Health & safety breach resulting in personnel injury or casualty",
    "Failure to sustain IT services",
    "Inadequate alignment between business requirement & IT",
    "Inadequate segregation of duties between IT Application Team",
    "Adequate IT governance framework​",
    "Rising costs (cost inflation)",
    "Inadequate Control over Software Licenses expose Ma'aden to legal implication of unauthorized use of unlicensed Software.",
    "Cash/fund management & cost of funding",
    "Availability of sufficient water supplies",
    "Inadequate process to handle emergency changes to the systems",
    "Marketability (Inability to market and sell our products effectively)",
    "Commodity price fluctuations",
    "Inability to attract, develop & retain human resources (Skills shortage)",
  ],
  LIKELIHOODS: [
    "1 - Rare",
    "2- Unlikely",
    "3- Possible",
    "4- Likely",
    "5- Almost Certain",
  ],
  IMPACTS: [
    "1- Very Low",
    "2- Low",
    "3- Moderate",
    "4- High",
    "5- Very High",
  ],
  FREQUENCIES: ["Daily", "Weekly", "Monthly ", "Quarterly", "Yearly"],
  RATINGS: [
    "Adequate-Excellent - 1 - Effective and efficient systems and processes adequately mitigate the risk",
    "Adequate-Good - 2-4 - Systems and processes exist which adequately mitigate the risk",
    "Inadequate-Partial - 5-7 - Systems and processes exist which only partially mitigates the risk",
    "Inadequate-Poor - 8-9 - Systems and processes exist but do not mitigate the risk",
    "Inadequate-Unsatisfactory - 10 - No systems and processes exist to manage the risk",
  ],
  STATUSES: ["On Track", "Off Track"],
}
